# Generated by Django 3.2.9 on 2021-11-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer_Data',
            new_name='customer',
        ),
    ]
