# Generated by Django 3.2.9 on 2021-11-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211118_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, null=True)),
                ('email', models.CharField(max_length=122, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('cnic', models.CharField(max_length=122, null=True)),
                ('password', models.CharField(max_length=122, null=True)),
            ],
        ),
    ]
