# Generated by Django 3.2.9 on 2021-12-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
